# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: woojean的博客
brief-intro: 好吃懒做，游手好闲。✍
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://woojean.com" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  woojean
email: 

description_footer:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge


# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 20
